[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
# [target.x86_64-unknown-linux-musl.openssl]
# rustc-link-lib = ["openssl"]
# rustc-link-search = ["/opt/homebrew/opt/openssl"]
# rustc-flags = "-L /opt/homebrew/opt/openssl/lib"
